import Foundation

/// Generates the typed Swift surface from the vendored contract artifacts.
///
/// Emission follows the sdk-python precedent — the contract (`schema.json` +
/// `manifest.json`), never the TypeScript — with the naming discipline the
/// acceptance criteria demand: every name comes from a schema `title` or the
/// enclosing property path, collisions are a hard error (never a counter),
/// and all iteration is sorted so regeneration is byte-identical.
public struct Codegen {

    public struct Output {
        /// filename → file content, e.g. `"Models.swift"` → source.
        public let files: [String: String]
    }

    let defs: [String: JSON]
    let methods: [JSON]
    let errorCodes: [String: JSON]

    // Accumulated named declarations: name → (source, provenance path,
    // canonical schema fingerprint for dedupe).
    private final class State {
        var declarations: [String: (source: String, path: String, fingerprint: String)] = [:]
    }
    private let state = State()

    // MARK: - Entry

    public static func generate(contractDirectory: URL) throws -> Output {
        func load(_ name: String) throws -> JSON {
            try JSON.parse(try Data(contentsOf: contractDirectory.appendingPathComponent(name)))
        }
        return try Codegen(
            schema: try load("schema.json"),
            manifest: try load("manifest.json"),
            errorCodes: try load("error-codes.json")
        ).run()
    }

    init(schema: JSON, manifest: JSON, errorCodes: JSON) throws {
        guard let defs = schema["$defs"]?.objectValue else {
            throw CodegenError.malformedContract("schema.json has no $defs")
        }
        guard let methods = manifest["methods"]?.arrayValue else {
            throw CodegenError.malformedContract("manifest.json has no methods array")
        }
        guard let codes = errorCodes.objectValue else {
            throw CodegenError.malformedContract("error-codes.json is not an object")
        }
        self.defs = defs
        self.methods = methods
        self.errorCodes = codes
    }

    func run() throws -> Output {
        // Emit every def except the `request`/`response` envelopes (AnyRequest
        // / AnyResponse unions — the typed methods make them redundant, and
        // nothing else references them).
        for name in defs.keys.sorted() where name != "request" && name != "response" {
            _ = try typeExpression(for: defs[name]!, hint: pascal(name), at: "$defs/\(name)")
        }

        let models = state.declarations.keys.sorted().map { state.declarations[$0]!.source }
        return Output(files: [
            "Models.swift": header + models.joined(separator: "\n\n") + "\n",
            "Methods.swift": header + (try emitMethods()) + "\n",
            "ErrorCodes.swift": header + emitErrorCodes() + "\n"
        ])
    }

    private var header: String {
        """
        // Generated by `swift run qvac-codegen` from the vendored contract/ —
        // DO NOT EDIT. Regenerate after refreshing the contract; CI fails if
        // this file is stale (`swift run qvac-codegen --check`).

        import Foundation


        """
    }

    // MARK: - Type resolution

    /// Returns the Swift type expression for a schema, registering named
    /// declarations along the way. `hint` is the PascalCase path-derived name
    /// used when the schema carries no `title`.
    func typeExpression(for schema: JSON, hint: String, at path: String) throws -> String {
        // $ref → the referenced def's type (by its title).
        if let ref = schema["$ref"]?.stringValue {
            let prefix = "schema.json#/$defs/"
            let local = "#/$defs/"
            let defName: String
            if ref.hasPrefix(prefix) { defName = String(ref.dropFirst(prefix.count)) }
            else if ref.hasPrefix(local) { defName = String(ref.dropFirst(local.count)) }
            else { throw CodegenError.unsupportedSchema("external $ref '\(ref)'", at: path) }
            guard let target = defs[defName] else {
                throw CodegenError.unsupportedSchema("dangling $ref '\(ref)'", at: path)
            }
            return try typeExpression(for: target, hint: pascal(defName), at: "$defs/\(defName)")
        }

        // Unions.
        if let arms = (schema["oneOf"] ?? schema["anyOf"])?.arrayValue {
            return try unionExpression(schema: schema, arms: arms, hint: hint, at: path)
        }

        // Enums. Numeric ones without `x-enum-varnames` have no usable case
        // names — they are validated numbers, so the primitive is the type.
        if let members = schema["enum"]?.arrayValue {
            let allStrings = members.allSatisfy { $0.stringValue != nil }
            if !allStrings && schema["x-enum-varnames"] == nil {
                let integral = members.allSatisfy {
                    if case .number(let value) = $0 { return value == value.rounded() }
                    return false
                }
                return integral ? "Int" : "Double"
            }
            return try emitStringEnum(schema: schema, hint: hint, at: path)
        }

        let type = schema["type"]?.stringValue
        switch type {
        case "string": return "String"
        case "number": return "Double"
        case "integer": return "Int"
        case "boolean": return "Bool"
        case "null": return "JSONValue"
        case "array":
            if let prefixItems = schema["prefixItems"]?.arrayValue {
                // One use in the contract (a bbox tuple). All-numeric → [Double].
                let allNumeric = prefixItems.allSatisfy {
                    ["number", "integer"].contains($0["type"]?.stringValue ?? "")
                }
                return allNumeric ? "[Double]" : "[JSONValue]"
            }
            if let items = schema["items"] {
                return "[\(try typeExpression(for: items, hint: hint + "Item", at: path + ".items"))]"
            }
            return "[JSONValue]"
        case "object", nil:
            if let properties = schema["properties"]?.objectValue, !properties.isEmpty {
                return try emitStruct(schema: schema, hint: hint, at: path)
            }
            if type == "object" {
                if let additional = schema["additionalProperties"], additional.objectValue != nil {
                    let value = try typeExpression(for: additional, hint: hint + "Value", at: path + ".additionalProperties")
                    return "[String: \(value)]"
                }
                return "[String: JSONValue]"
            }
            return "JSONValue"  // untyped: {}
        default:
            throw CodegenError.unsupportedSchema("type '\(type ?? "?")'", at: path)
        }
    }

    // MARK: - Unions

    private func unionExpression(schema: JSON, arms: [JSON], hint: String, at path: String) throws -> String {
        // Nullability: exactly two arms, one `{"type":"null"}`.
        let nullIndex = arms.firstIndex { $0["type"]?.stringValue == "null" }
        if arms.count == 2, let nullIndex {
            let other = arms[1 - nullIndex]
            let inner = try typeExpression(for: other, hint: hint, at: path)
            return inner.hasSuffix("?") ? inner : inner + "?"
        }

        // Same-primitive unions are constraints, not shapes — `predict` is
        // `anyOf: [const -1, const -2, integer ≥ 1]`, which in Swift is just
        // a number. Collapse before inventing an enum nobody wants.
        let primitiveKinds = Set(arms.compactMap { resolved($0)["type"]?.stringValue })
        if primitiveKinds == ["integer"] { return "Int" }
        if primitiveKinds.subtracting(["number", "integer"]).isEmpty, !primitiveKinds.isEmpty,
           arms.allSatisfy({ resolved($0)["type"]?.stringValue != nil }) {
            return "Double"
        }
        if primitiveKinds == ["string"], arms.allSatisfy({ resolved($0)["enum"] == nil }) { return "String" }
        if primitiveKinds == ["boolean"] { return "Bool" }

        // Untitled unions take a `Variants` suffix: the exporter titles union
        // *arms* by the same property path (see `diffusionStream.request
        // .upscale`), so the bare hint would collide with its own arm.
        let name = schema["title"]?.stringValue ?? (hint + "Variants")

        // Discriminated: a key present in every arm as a *distinct* string
        // const. `rag.request` shows why distinctness matters — every arm
        // also carries `type: "rag"`, which discriminates nothing.
        if let discriminator = discriminatorKey(arms: arms) {
            return try registerOnce(name: name, schema: schema, at: path) {
                try emitDiscriminatedUnion(name: name, arms: arms, key: discriminator, at: path)
            }
        }

        // Shape union: decode attempts ordered most-constrained-first.
        return try registerOnce(name: name, schema: schema, at: path) {
            try emitShapeUnion(name: name, arms: arms, at: path)
        }
    }

    private func discriminatorKey(arms: [JSON]) -> String? {
        var candidates: Set<String>?
        for arm in arms {
            guard let properties = resolved(arm)["properties"]?.objectValue else { return nil }
            let constKeys = Set(properties.keys.filter { properties[$0]?["const"]?.stringValue != nil })
            candidates = candidates.map { $0.intersection(constKeys) } ?? constKeys
        }
        guard let keys = candidates else { return nil }
        // Prefer the conventional names, then alphabetical, requiring
        // distinct values across arms.
        for key in ["operation", "type"] + keys.sorted() where keys.contains(key) {
            let values = arms.map { resolved($0)["properties"]?[key]?["const"]?.stringValue }
            if Set(values.compactMap { $0 }).count == arms.count { return key }
        }
        return nil
    }

    private func resolved(_ schema: JSON) -> JSON {
        guard let ref = schema["$ref"]?.stringValue,
              let defName = ref.components(separatedBy: "$defs/").last,
              let target = defs[defName] else { return schema }
        return target
    }

    private func emitDiscriminatedUnion(name: String, arms: [JSON], key: String, at path: String) throws -> String {
        struct Arm { let tag: String; let caseName: String; let type: String }
        var built: [Arm] = []
        for (index, armSchema) in arms.enumerated() {
            let arm = resolved(armSchema)
            let tag = arm["properties"]![key]!["const"]!.stringValue!
            let caseName = identifier(from: tag)
            let type = try typeExpression(
                for: armSchema, hint: name + pascal(tag), at: "\(path).arm(\(tag))")
            if built.contains(where: { $0.caseName == caseName }) {
                throw CodegenError.nameCollision(name: caseName, first: path, second: "\(path)[\(index)]")
            }
            built.append(Arm(tag: tag, caseName: caseName, type: type))
        }

        var out = "/// Discriminated on `\(key)`. From `\(path)`.\n"
        out += "public enum \(name): Codable, Equatable, Sendable {\n"
        for arm in built { out += "    case \(arm.caseName)(\(arm.type))\n" }
        out += """

            public init(from decoder: Decoder) throws {
                let container = try decoder.container(keyedBy: AnyCodingKey.self)
                let tag = try container.decode(String.self, forKey: AnyCodingKey("\(key)"))
                switch tag {\n
        """
        for arm in built {
            out += "        case \(quoted(arm.tag)): self = .\(arm.caseName)(try \(arm.type)(from: decoder))\n"
        }
        out += """
                default:
                    throw DecodingError.dataCorrupted(.init(
                        codingPath: decoder.codingPath,
                        debugDescription: "\(name): unknown \(key) '\\(tag)'"))
                }
            }

            public func encode(to encoder: Encoder) throws {
                switch self {\n
        """
        for arm in built {
            out += "        case .\(arm.caseName)(let value): try value.encode(to: encoder)\n"
        }
        out += "        }\n    }\n}"
        return out
    }

    private func emitShapeUnion(name: String, arms: [JSON], at path: String) throws -> String {
        struct Arm { let caseName: String; let type: String; let requiredCount: Int; let isObject: Bool }
        var built: [Arm] = []
        for (index, armSchema) in arms.enumerated() {
            let arm = resolved(armSchema)
            let type = try typeExpression(for: armSchema, hint: name + "Arm\(index)", at: "\(path)[\(index)]")
            let caseName = caseName(forTypeExpression: type)
            if built.contains(where: { $0.caseName == caseName }) {
                throw CodegenError.nameCollision(name: "\(name).\(caseName)", first: path, second: "\(path)[\(index)]")
            }
            built.append(Arm(
                caseName: caseName,
                type: type,
                requiredCount: arm["required"]?.arrayValue?.count ?? 0,
                isObject: arm["properties"]?.objectValue != nil
            ))
        }

        // Decode order: objects before primitives, more required fields first
        // (an all-optional struct decodes from nearly anything, so it must be
        // tried last among the objects), then stable by case name.
        let decodeOrder = built.sorted {
            if $0.isObject != $1.isObject { return $0.isObject }
            if $0.requiredCount != $1.requiredCount { return $0.requiredCount > $1.requiredCount }
            return $0.caseName < $1.caseName
        }

        var out = "/// Undiscriminated union — decoded most-constrained-first. From `\(path)`.\n"
        out += "public enum \(name): Codable, Equatable, Sendable {\n"
        for arm in built { out += "    case \(arm.caseName)(\(arm.type))\n" }
        out += "\n    public init(from decoder: Decoder) throws {\n"
        for arm in decodeOrder {
            out += "        if let value = try? \(arm.type)(from: decoder) { self = .\(arm.caseName)(value); return }\n"
        }
        let tried = decodeOrder.map(\.type).joined(separator: ", ")
        out += """
                throw DecodingError.dataCorrupted(.init(
                    codingPath: decoder.codingPath,
                    debugDescription: "\(name): no arm matched (tried \(tried))"))
            }

            public func encode(to encoder: Encoder) throws {
                switch self {\n
        """
        for arm in built {
            out += "        case .\(arm.caseName)(let value): try value.encode(to: encoder)\n"
        }
        out += "        }\n    }\n}"
        return out
    }

    // MARK: - Structs

    private func emitStruct(schema: JSON, hint: String, at path: String) throws -> String {
        let name = schema["title"]?.stringValue ?? hint
        return try registerOnce(name: name, schema: schema, at: path) {
            let properties = schema["properties"]!.objectValue!
            let required = Set(schema["required"]?.arrayValue?.compactMap(\.stringValue) ?? [])

            struct Field {
                let wireName: String
                let swiftName: String
                let type: String
                let defaultLiteral: String?
                let documentation: String?
            }
            var fields: [Field] = []

            for wireName in properties.keys.sorted() {
                let property = properties[wireName]!
                // `{"not": {}}` marks a field as forbidden in this variant
                // (loadModel's two arms); nothing to store.
                if property["not"] != nil, property.objectValue?.count == 1 { continue }

                let isRequired = required.contains(wireName)
                let swiftName = identifier(from: wireName)
                var type: String
                var defaultLiteral: String?

                if let constValue = property["const"]?.stringValue {
                    // Discriminators and fixed tags: carried as stored
                    // defaults so callers never have to spell them.
                    type = isRequired ? "String" : "String?"
                    defaultLiteral = quoted(constValue)
                } else {
                    type = try typeExpression(
                        for: property, hint: name + pascal(wireName), at: "\(path).\(wireName)")
                    if !isRequired && !type.hasSuffix("?") { type += "?" }
                    defaultLiteral = isRequired ? nil : "nil"
                }
                fields.append(Field(
                    wireName: wireName, swiftName: swiftName, type: type,
                    defaultLiteral: defaultLiteral,
                    documentation: property["description"]?.stringValue))
            }

            var out = ""
            if let description = schema["description"]?.stringValue {
                out += "/// \(sanitizeDocLine(description))\n"
            }
            out += "/// From `\(path)`.\n"
            out += "public struct \(name): Codable, Equatable, Sendable {\n"
            for field in fields {
                if let documentation = field.documentation {
                    out += "    /// \(sanitizeDocLine(documentation))\n"
                }
                out += "    public var \(escaped(field.swiftName)): \(field.type)"
                if let defaultLiteral = field.defaultLiteral { out += " = \(defaultLiteral)" }
                out += "\n"
            }

            if fields.contains(where: { $0.swiftName != $0.wireName }) {
                out += "\n    enum CodingKeys: String, CodingKey {\n"
                for field in fields {
                    out += field.swiftName == field.wireName
                        ? "        case \(escaped(field.swiftName))\n"
                        : "        case \(escaped(field.swiftName)) = \(quoted(field.wireName))\n"
                }
                out += "    }\n"
            }

            out += "\n    public init(\n"
            out += fields.map { field in
                var parameter = "        \(escaped(field.swiftName)): \(field.type)"
                if let defaultLiteral = field.defaultLiteral { parameter += " = \(defaultLiteral)" }
                return parameter
            }.joined(separator: ",\n")
            out += "\n    ) {\n"
            for field in fields {
                out += "        self.\(escaped(field.swiftName)) = \(escaped(field.swiftName))\n"
            }
            out += "    }\n}"
            return out
        }
    }

    // MARK: - String enums

    private func emitStringEnum(schema: JSON, hint: String, at path: String) throws -> String {
        let name = schema["title"]?.stringValue ?? hint
        return try registerOnce(name: name, schema: schema, at: path) {
            let members = schema["enum"]!.arrayValue!
            let varnames = schema["x-enum-varnames"]?.arrayValue?.compactMap(\.stringValue)
            if let varnames, varnames.count != members.count {
                throw CodegenError.malformedContract("x-enum-varnames length mismatch at \(path)")
            }

            // String enums are the norm; `Verbosity` is numeric ([0,1,2,3]
            // with varnames), so integral raw values are supported when every
            // member is a whole number and varnames supply the case names.
            let stringValues = members.compactMap(\.stringValue)
            let rawType: String
            let rawLiterals: [String]
            let fallbackNames: [String]?
            if stringValues.count == members.count {
                rawType = "String"
                rawLiterals = stringValues.map(quoted)
                fallbackNames = stringValues
            } else {
                let numbers: [Int] = try members.map {
                    guard case .number(let value) = $0, value == value.rounded() else {
                        throw CodegenError.unsupportedSchema("enum with mixed or fractional members", at: path)
                    }
                    return Int(value)
                }
                guard varnames != nil else {
                    throw CodegenError.unsupportedSchema("numeric enum without x-enum-varnames", at: path)
                }
                rawType = "Int"
                rawLiterals = numbers.map(String.init)
                fallbackNames = nil
            }

            var out = "/// From `\(path)`.\n"
            out += "public enum \(name): \(rawType), Codable, Equatable, Sendable, CaseIterable {\n"
            var seen: Set<String> = []
            for (index, rawLiteral) in rawLiterals.enumerated() {
                let caseName = identifier(from: varnames?[index] ?? fallbackNames![index])
                guard seen.insert(caseName).inserted else {
                    throw CodegenError.nameCollision(name: "\(name).\(caseName)", first: path, second: path)
                }
                out += "    case \(escaped(caseName)) = \(rawLiteral)\n"
            }
            out += "}"
            return out
        }
    }

    // MARK: - Registration

    /// Registers a named declaration exactly once. The same schema reached by
    /// two paths reuses the name; two *different* schemas wanting one name is
    /// the collision the acceptance criteria forbid resolving with a counter.
    private func registerOnce(name: String, schema: JSON, at path: String, render: () throws -> String) throws -> String {
        let fingerprint = canonical(schema)
        if let existing = state.declarations[name] {
            guard existing.fingerprint == fingerprint else {
                throw CodegenError.nameCollision(name: name, first: existing.path, second: path)
            }
            return name
        }
        // Reserve the name before rendering: self-references find the entry.
        state.declarations[name] = (source: "", path: path, fingerprint: fingerprint)
        let source = try render()
        state.declarations[name] = (source: source, path: path, fingerprint: fingerprint)
        return name
    }

    private func canonical(_ json: JSON) -> String {
        switch json {
        case .object(let fields):
            return "{" + fields.keys.sorted().map { "\(quoted($0)):\(canonical(fields[$0]!))" }.joined(separator: ",") + "}"
        case .array(let items):
            return "[" + items.map(canonical).joined(separator: ",") + "]"
        case .string(let value): return quoted(value)
        case .number(let value): return "\(value)"
        case .bool(let value): return "\(value)"
        case .null: return "null"
        }
    }
}
