import XCTest
@testable import QVACWire

/// The fixture is generated by the *reference JS encoder* (`bare-rpc` +
/// `compact-encoding`), not by this implementation. That is the whole point:
/// a round-trip test against ourselves would pass just as happily with the
/// endianness backwards.
///
/// Regenerate with `Scripts/generate-fixture.js`.
final class WireCodecTests: XCTestCase {

    struct Fixture: Decodable {
        struct Expect: Decodable {
            let type: UInt64
            let id: UInt64
            let command: UInt64?
            let stream: UInt64
            let dataHex: String?
            let errno: Int64?
            let code: String?
            let message: String?
        }
        struct Frame: Decodable {
            let name: String
            let hex: String
            let expect: Expect
        }
        let frames: [Frame]
        let concatenated: String
        let frameCount: Int
    }

    static var fixture: Fixture = {
        let url = Bundle.module.url(forResource: "fixture", withExtension: "json")!
        return try! JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }()

    // MARK: - Encoding

    /// Byte-for-byte equality with the reference encoder across every varint
    /// width boundary, the zigzag errno range, and payload sizes that straddle
    /// the length-prefix transitions.
    func testEncodeMatchesReferenceEncoder() throws {
        for f in Self.fixture.frames {
            let expected = Data(hex: f.hex)!
            let message = try Self.message(from: f.expect)
            XCTAssertEqual(
                WireCodec.encode(message), expected,
                "encoding diverged for \(f.name)"
            )
        }
    }

    func testDecodeMatchesReferenceEncoder() throws {
        for f in Self.fixture.frames {
            let decoded = try WireCodec.decode(frame: Data(hex: f.hex)!)
            XCTAssertEqual(decoded.type.rawValue, f.expect.type, f.name)
            XCTAssertEqual(decoded.id, f.expect.id, f.name)
            XCTAssertEqual(decoded.flags.rawValue, f.expect.stream, f.name)
            if let hex = f.expect.dataHex {
                XCTAssertEqual(decoded.payload, Data(hex: hex)!, f.name)
            }
            if let errno = f.expect.errno {
                XCTAssertEqual(decoded.error?.errno, errno, f.name)
                XCTAssertEqual(decoded.error?.code, f.expect.code, f.name)
                XCTAssertEqual(decoded.error?.message, f.expect.message, f.name)
            }
        }
    }

    func testRoundTripIsIdentity() throws {
        for f in Self.fixture.frames {
            let original = Data(hex: f.hex)!
            let reencoded = WireCodec.encode(try WireCodec.decode(frame: original))
            XCTAssertEqual(reencoded, original, "round-trip lost information for \(f.name)")
        }
    }

    // MARK: - Varint boundaries
    //
    // Each of these is one byte away from a width change. Off-by-ones here
    // produce a framing desync that surfaces hundreds of milliseconds later as
    // an unrelated-looking parse failure.

    func testVarintWidthBoundaries() {
        for n: UInt64 in [0, 1, 0xfc, 0xfd, 0xfe, 0xff, 0x100, 0xffff, 0x1_0000,
                          0xffff_ffff, 0x1_0000_0000, UInt64.max] {
            var out = Data()
            CompactEncoding.encode(uint: n, into: &out)
            XCTAssertEqual(out.count, CompactEncoding.encodedSize(uint: n),
                           "size prediction wrong for \(n)")
            let decoded = out.withUnsafeBytes { raw -> UInt64 in
                var r = ByteReader(raw)
                return try! r.readUInt()
            }
            XCTAssertEqual(decoded, n)
        }
    }

    func testZigzagRoundTrip() {
        for n: Int64 in [0, 1, -1, 2, -2, 127, -128, 52401, -52401,
                         Int64(Int32.max), Int64(Int32.min), Int64.max, Int64.min + 1] {
            XCTAssertEqual(CompactEncoding.unzigzag(CompactEncoding.zigzag(n)), n, "\(n)")
        }
        // Anchored to observed reference output, not just self-consistency.
        XCTAssertEqual(CompactEncoding.zigzag(52401), 104802)
        XCTAssertEqual(CompactEncoding.zigzag(-3), 5)
    }

    // MARK: - Reassembly
    //
    // The transport delivers arbitrary chunk boundaries. Chunk size 1 is not a
    // silly edge case: it is the cheapest way to prove no code path assumes a
    // frame header arrives intact.

    func testReassemblyUnderAdversarialChunking() throws {
        let stream = Data(hex: Self.fixture.concatenated)!
        for chunkSize in [1, 2, 3, 5, 7, 13, 64, 4096, stream.count] {
            var decoder = FrameDecoder()
            var count = 0
            var offset = 0
            while offset < stream.count {
                let end = min(offset + chunkSize, stream.count)
                count += try decoder.append(stream[offset ..< end]).count
                offset = end
            }
            XCTAssertEqual(count, Self.fixture.frameCount,
                           "lost frames at chunk size \(chunkSize)")
            XCTAssertEqual(decoder.bufferedCount, 0,
                           "residue left buffered at chunk size \(chunkSize)")
        }
    }

    /// A single read can carry many frames. Returning only the first one
    /// deadlocks as soon as the peer stops sending.
    func testDrainsAllFramesFromOneChunk() throws {
        var decoder = FrameDecoder()
        let frames = try decoder.append(Data(hex: Self.fixture.concatenated)!)
        XCTAssertEqual(frames.count, Self.fixture.frameCount)
    }

    func testEmptyAndPartialAppendsAreSafe() throws {
        var decoder = FrameDecoder()
        XCTAssertEqual(try decoder.append(Data()).count, 0)
        let frame = Data(hex: Self.fixture.frames[0].hex)!
        XCTAssertEqual(try decoder.append(frame.prefix(2)).count, 0)
        XCTAssertEqual(try decoder.append(Data()).count, 0)
        XCTAssertEqual(try decoder.append(frame.dropFirst(2)).count, 1)
    }

    func testOversizedFrameIsRejected() {
        var decoder = FrameDecoder(maxFrameSize: 64)
        var bogus = Data()
        CompactEncoding.appendLE(UInt32(1_000_000), to: &bogus)
        XCTAssertThrowsError(try decoder.append(bogus)) { error in
            guard case FrameDecoder.Error.frameTooLarge = error else {
                return XCTFail("expected frameTooLarge, got \(error)")
            }
        }
    }

    // MARK: - NDJSON

    func testNDJSONSplitsAcrossChunkBoundaries() {
        var splitter = NDJSONSplitter()
        var records = splitter.append(Data(#"{"a":1}"#.utf8))
        XCTAssertTrue(records.isEmpty, "must not emit before the delimiter")
        records = splitter.append(Data("\n{\"b\":2}\n".utf8))
        XCTAssertEqual(records.count, 2)
        XCTAssertEqual(String(data: records[0], encoding: .utf8), #"{"a":1}"#)
    }

    /// The reference Python client emits a trailing unterminated record; a
    /// splitter without `flush()` silently drops the final token of a stream.
    func testNDJSONFlushesUnterminatedTail() {
        var splitter = NDJSONSplitter()
        _ = splitter.append(Data("{\"a\":1}\n{\"b\":2}".utf8))
        XCTAssertEqual(String(data: splitter.flush()!, encoding: .utf8), #"{"b":2}"#)
        XCTAssertNil(splitter.flush(), "flush must be idempotent")
    }

    func testNDJSONSkipsBlankLines() {
        var splitter = NDJSONSplitter()
        let records = splitter.append(Data("{\"a\":1}\n\n  \n{\"b\":2}\n".utf8))
        XCTAssertEqual(records.count, 2)
    }

    func testNDJSONByteAtATime() {
        var splitter = NDJSONSplitter()
        let input = Data("{\"a\":1}\n{\"b\":2}\n{\"c\":3}\n".utf8)
        var count = 0
        for byte in input { count += splitter.append(Data([byte])).count }
        XCTAssertEqual(count, 3)
    }

    // MARK: - Semantics

    func testEventsAreDistinguishedFromRequests() {
        let event = WireMessage(type: .request, id: 0, command: 5, payload: Data())
        XCTAssertTrue(event.isEvent, "id 0 is fire-and-forget; awaiting a reply leaks")
        XCTAssertFalse(WireMessage.request(id: 1, command: 5, payload: Data()).isEvent)
    }

    func testStreamFlagsCompose() {
        let flags: StreamFlags = [.open, .request]
        XCTAssertEqual(flags.rawValue, 0x101, "OPEN|REQUEST is one legitimate value")
        XCTAssertTrue(StreamFlags.none.isUnary)
        XCTAssertFalse(StreamFlags.data.isUnary)
    }

    // MARK: - Helpers

    static func message(from e: Fixture.Expect) throws -> WireMessage {
        WireMessage(
            type: MessageType(rawValue: e.type)!,
            id: e.id,
            command: e.command,
            flags: StreamFlags(rawValue: e.stream),
            payload: e.dataHex.flatMap { Data(hex: $0) },
            error: e.errno.map { WireError(message: e.message ?? "", code: e.code ?? "", errno: $0) }
        )
    }
}

extension Data {
    init?(hex: String) {
        guard hex.count % 2 == 0 else { return nil }
        var out = Data(capacity: hex.count / 2)
        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2)
            guard let byte = UInt8(hex[index ..< next], radix: 16) else { return nil }
            out.append(byte)
            index = next
        }
        self = out
    }
}
